// packages/examples/h5/src/components/page.tsx
import React, { useEffect, useRef, useState } from 'react';
import './page.less';
interface OptionProps {
  key: string;
  desc: string;
  name: string;
  show?: boolean;
  attr?: { [key: string]: unknown };
}
interface ColorType extends OptionProps {
  type: 'color';
  value: string;
  list?: { label: string; value: string; [key: string]: unknown }[];
}
interface RadiusType extends OptionProps {
  type: 'radius';
  value: number;
  min?: number;
  max?: number;
}

interface RadioType extends OptionProps {
  type: 'radio';
  value: unknown;
  list: {
    label: string;
    value: unknown;
    hiddenItems?: string[];
    attr?: { [key: string]: unknown };
    [key: string]: unknown;
  }[];
  currentIndex?: number;
}
export type OptionType = ColorType | RadiusType | (RadioType & { [key: string]: unknown });
function formatOption(data: OptionType[]): OptionType[] {
  const options: (OptionType & { show?: boolean })[] = data;
  options.forEach(item => {
    item.show = true;
  });
  options.forEach(element => {
    if (element.type === 'color') {
      element.value = element.value || '#fa2c19';
    } else if (element.type === 'radius') {
      element.value = element.value || 0;
    } else if (element.type === 'radio') {
      const target = element.list.find((item, index) => {
        if (item.value === element.value) {
          element.currentIndex = index;
          return true;
        }
        return false;
      });
      if (!target?.hiddenItems) return;
      target.hiddenItems.forEach(it => {
        const item = options.find(el => el.key === it);
        // 只有当他自己显示的情况下，才能控制他的hiddenItems
        element.show && item && (item.show = false);
      });
    }
  });
  return options;
}

const App = ({
  center = true,
  children,
  options,
  change,
}: {
  center?: boolean;
  options: OptionType[];
  children?: React.ReactNode;
  change: (params: { [key: string]: unknown }) => void;
}) => {
  const [newOption, setOptions] = useState<OptionType[]>([]);
  const refOption = useRef<OptionType[]>([]);
  const ref = useRef<Set<unknown>>(new Set());
  const sliderKey = useRef('');
  const sendEvent = (eventName = 'change') => {
    const curOption = formatOption(refOption.current);
    const attr = curOption.reduce((prev, curr) => {
      if (!curr.show) return prev;
      prev[curr.key] = curr.value;
      if (curr.attr) {
        prev = { ...prev, ...curr.attr };
      }
      if (curr.type === 'radio') {
        const item = curr.list.find(el => el.value === curr.value);
        const attr = item?.attr;
        if (item && attr) {
          prev = { ...prev, ...attr };
        }
      }
      return prev;
    }, {} as { [key: string]: unknown });
    setOptions(curOption);
    refOption.current = curOption;
    ref.current = new Set(Array.from(ref.current).concat(Object.keys(attr)));
    change(attr);
  };
  const onClick: React.MouseEventHandler<HTMLElement> = event => {
    if (event.target instanceof HTMLElement) {
      const {
        target: {
          dataset: { value, key },
        },
      } = event;
      const target = newOption.find(el => el.key === key);
      if (!target) return;
      let val: boolean | string = value as string;
      if (value === JSON.stringify(false)) {
        val = false;
      } else if (value === JSON.stringify(true)) {
        val = true;
      }
      if (target.value == val) {
        sendEvent('repeat');
        return;
      }
      const curOption = newOption.map(el =>
        el.key === key ? { ...el, value: typeof el.value === 'number' ? Number(val) : val } : el,
      );
      refOption.current = curOption as OptionType[];
      sendEvent();
    }
  };

  const onChangeRadius = (event: Event) => {
    if (event.target instanceof HTMLElement) {
      let key = event.target.dataset.key;
      let {
        detail: { value },
      } = event as CustomEvent<HTMLTiSliderElement>;
      key = key || sliderKey.current;

      refOption.current = refOption.current.map(el => (el.key === key ? { ...el, value } : el)) as OptionType[];

      sendEvent();
    }
  };

  useEffect(() => {
    const newOption = formatOption(options);
    setOptions(newOption);
    refOption.current = newOption;
    sendEvent();
  }, [options]);

  return (
    <div className="page">
      <div className={`page-container ${center ? 'center' : ''}`}>{children}</div>
      <div className="menu">
        <div style={{ height: '50px' }} />
        {newOption.map((item, idx) => {
          if (!item.show) {
            return null;
          }
          return (
            <div className="drawer" key={idx}>
              <div className="title">
                <div className="desc">{item.desc}</div>
                <div className="name">{item.name}</div>
              </div>
              {item.type === 'radio' && <Radio id={item.key} list={item.list} value={item.value} onClick={onClick} />}
              {item.type === 'color' && <Color id={item.key} list={item.list} value={item.value} onClick={onClick} />}
              {item.type === 'radius' && (
                <Radius
                  id={item.key}
                  min={item.min}
                  max={item.max}
                  value={item.value as unknown as number}
                  onChange={onChangeRadius}
                />
              )}
            </div>
          );
        })}
        <div className="footer" />
      </div>
    </div>
  );
};
export default App;

const Radio = ({
  id,
  list,
  value,
  onClick,
}: {
  id: string;
  list: { label: string; value: unknown }[];
  value: unknown;
  onClick: React.MouseEventHandler<HTMLElement>;
}) => {
  return (
    <div className="radio-box">
      {list.map((radio, idx) => {
        return (
          <div
            key={idx}
            id={`item-${idx}`}
            data-key={id}
            data-value={radio.value}
            className={`radio ${value === radio.value ? 'checked' : ''}`}
            onClick={onClick}
          >
            {radio.label}
          </div>
        );
      })}
    </div>
  );
};
const Color = ({
  id,
  list,
  value,
  onClick,
}: {
  id: string;
  list?: { label: string; value: string }[];
  value: unknown;
  onClick: React.MouseEventHandler<HTMLElement>;
}) => {
  const colors: { label: string; value: string }[] = [
    { label: 'red', value: '#fa2c19' },
    { label: 'orange', value: '#ffa300' },
    { label: 'green', value: '#07c160' },
    { label: 'blue', value: '#2a6ae9' },
    { label: 'grey', value: '#9e9e9e' },
  ];
  return (
    <div className="colors">
      {(list || colors).map((color, idx) => {
        return (
          <div
            key={idx}
            className={`color ${value === color.value ? 'checked' : ''}`}
            data-value={color.value}
            data-key={id}
            onClick={onClick}
            style={{ color: color.value, background: color.value }}
          ></div>
        );
      })}
    </div>
  );
};

const Radius = ({
  id,
  max,
  min,
  value,
  onChange,
}: {
  id: string;
  max?: number;
  min?: number;
  value: number;
  onChange: EventListener;
}) => {
  const ref = useRef<HTMLTiSliderElement>();
  useEffect(() => {
    ref.current?.addEventListener('change', onChange);
    return () => {
      ref.current?.removeEventListener('change', onChange);
    };
  }, []);
  return (
    <div className="radius" data-key={id}>
      <ti-slider ref={elem => (ref.current = elem)} max={max || 100} min={min || 0} value={value} data-key={id} />
    </div>
  );
};

// packages/examples/vue3/src/components/page.vue
<template>
  <div class="page" :class="pageClass">
    <div :class="containerClassName">
      <slot />
    </div>

    <div class="menu">
      <div class="inner-menu">
        <div :style="{ height: '25px' }" />
        <div v-for="item in dataSource.options">
          <div class="drawer" v-if="item.show">
            <div class="title">
              <div class="desc">{{ item.desc }}</div>
              <div class="name">{{ item.name }}</div>
            </div>
            <CustomRadio
              v-if="item.type === 'radio'"
              :list="item.list"
              :value="item.value"
              @click="(value: string) => onClick({key:item.key, value})"
            />
            <CustomColor
              v-if="item.type === 'color'"
              :list="item.list"
              :value="item.value"
              @click="(value: string) => onClick({key:item.key, value})"
            />
            <CustomRadius
              v-if="item.type === 'radius'"
              :min="item.min"
              :max="item.max"
              :value="item.value"
              @change="(value: HTMLTiSliderElement) => onChangeRadius({key: item.key, value})"
            />
          </div>
        </div>
        <div class="footer" />
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import CustomRadio from './radio.vue';
import CustomColor from './color.vue';
import CustomRadius from './radius.vue';
import type { IPageProps, IOptionType } from './page.interface';
import { defineProps, PropType, reactive, ref, watchEffect } from 'vue';
import { formatOption } from './utils';

interface IProps extends IPageProps {}

const emit = defineEmits<{ (event: 'change', attr: any): void }>();
const { options, center } = defineProps({
  options: {
    required: true,
    type: Object as PropType<IProps['options']>,
  },
  change: Function as PropType<IProps['change']>,
  center: {
    type: Boolean,
    default: true,
  },
  pageClass: {
    type: String,
    default: '',
  },
});

const containerClassName = `page-container ${center ? 'center' : ''}`;

const dataSource = reactive<{ options: IOptionType[] }>({
  options: [],
});

interface Params<T = string | number> {
  key: string;
  value: T;
}

const sendEvent = (optionsParams: IOptionType[] = options, eventName: 'change' | 'repeat' = 'change') => {
  const curOption = formatOption(optionsParams);
  const attr = curOption.reduce<Record<string, any>>((prev, curr) => {
    if (!curr.show) return prev;

    prev[curr.key] = curr.value;

    if (curr.attr) {
      prev = { ...prev, ...curr.attr };
    }

    if (curr.type === 'radio') {
      const item = curr.list.find(el => el.value === curr.value);
      const attr = item?.attr;

      if (item && attr) {
        prev = { ...prev, ...attr };
      }
    }
    return prev;
  }, {});
  dataSource.options = curOption;
  emit('change', attr);
};

const onClick = (params: Params) => {
  const { key, value } = params;
  const target = dataSource.options.find(el => el.key === key);
  if (!target) return;

  const val = value === 'true' ? true : value === 'false' ? false : value;

  if (target.value === val) {
    return;
  }
  const curOption = dataSource.options.map(el =>
    el.key === key ? { ...el, value: typeof el.value === 'number' ? Number(val) : val } : el,
  );

  dataSource.options = curOption as IOptionType[];
  sendEvent(dataSource.options);
};

const onChangeRadius = (params: Params<CustomEvent<HTMLTiSliderElement>>) => {
  let { key, value: e } = params;
  const target = dataSource.options.find(el => el.key === key);
  if (!target) return;

  if (e.target instanceof HTMLElement) {
    let {
      detail: { value },
    } = e as CustomEvent<HTMLTiSliderElement>;

    dataSource.options = dataSource.options.map(el => (el.key === key ? { ...el, value } : el)) as IOptionType[];

    sendEvent(dataSource.options);
  }
};

watchEffect(() => {
  if (options) {
    const formatedOption = formatOption(options);
    dataSource.options = formatedOption;
    sendEvent(formatedOption);
  }
});
</script>

<style lang="less">
.page {
  width: 100vw;
  min-height: 100vh;

  background-color: #f9f9f9;
}

.page-container {
  position: relative;
  height: 40vh;
}

.page-container.center {
  display: flex;
  align-items: center;
  justify-content: center;
  height: calc(40vh + 44px);
  margin-top: -44px;
}

.page-container:empty {
  display: none;
}

.menu {
  position: relative;
  box-sizing: border-box;
  height: 60vh;
  padding-top: 10px;
  overflow: hidden;

  border-radius: 32px 32px 0 0;

  background: #fff;
  box-shadow: 0 -8px 40px 0 rgba(0, 0, 0, 6%);
}

.inner-menu {
  height: 100%;
  overflow-y: auto;
}

.menu::before {
  content: '';

  position: absolute;
  z-index: 1;
  top: 0;
  right: 40px;
  left: 40px;
  height: 50px;

  background: linear-gradient(0deg, rgba(255, 255, 255, 0%) 0%, #fff 100%);
}

.menu::after {
  content: '';

  position: absolute;
  z-index: 1;
  right: 40px;
  bottom: 0;
  left: 40px;
  height: 68px;

  background: linear-gradient(180deg, rgba(255, 255, 255, 0%) 0%, #fff 100%);
}

.footer {
  height: 34px;
  padding-bottom: constant(safe-area-inset-bottom);
  /* 兼容 iOS < 11.2 */
  padding-bottom: env(safe-area-inset-bottom);
  /* 兼容 iOS >= 11.2 */
}

.page-container:empty + .menu::before {
  content: none;
}

.page-container:empty + .menu::after {
  content: none;
}

.page-container:empty + .menu .footer {
  height: 28px;
  padding-bottom: 0;
}

.drawer {
  display: flex;
  position: relative;
  z-index: 0;
  box-sizing: border-box;
  align-items: center;
  height: 134px;
  margin: 0 48px 20px;
  overflow: hidden;

  border-radius: 12px;

  background: #f9f9f9;
}

.page-container:empty + .menu {
  height: auto;
  padding-top: 0;

  border-radius: 0;

  box-shadow: none;
}

/* .drawer.first {
    margin-top: 50px;
  }
  .drawer.last {
    margin-bottom: 100px;
  } */
.drawer::before {
  content: '';

  position: absolute;
  top: 0;
  left: 0;
  box-sizing: border-box;
  width: 200%;
  height: 200%;

  transform: scale(0.5);
  transform-origin: left top;

  border: 2px solid #f2f2f2;
  border-radius: 24px;
}

.title {
  box-sizing: border-box;
  width: 160px;
  padding-left: 32px;
}

.desc {
  color: #212121;
  font-size: 26px;
  font-weight: 500;
  line-height: 30px;
}

.name {
  margin-top: 6px;

  color: #c4c4c4;
  font-size: 20px;
  line-height: 24px;
}

.operation {
  flex: 1;
}
</style>
