// packages/examples/vue3/src/pages/virtual-list/index.vue
<template>
  <TiVirtualList ref="virtualListRef" @load="load"></TiVirtualList>
</template>
<script lang="ts" setup>
import { ref, onMounted, ComponentPublicInstance, watchEffect } from 'vue';
import { TiVirtualList } from '@titian-design/mobile-vue';

const virtualListRef = ref<ComponentPublicInstance<HTMLTiVirtualListElement> | null>(null);
const data = ref<number[]>([]);

const load = () => {
  data.value = data.value.concat(
    Array(10)
      .fill(0)
      .map((_, idx) => (data.value[data.value.length - 1] || 0) + idx + 1),
  );
};

watchEffect(() => {
  virtualListRef.value?.$el.setListData(data.value);
});

onMounted(() => {
  virtualListRef.value?.$el.setRenderItem(
    (item: number | string) => `<div style="height: 50px; width: 100%;">${item}</div>`,
  );
});
</script>

// packages/examples/react/src/pages/virtual-list/index.tsx
import { FC, useCallback, useEffect, useRef, useState } from 'react';
import { TiVirtualList } from '@titian-design/mobile-react';

export const VirtualListPage: FC = () => {
  const virtualListRef = useRef<HTMLTiVirtualListElement>(null);
  const [data, setData] = useState<number[]>([]);

  useEffect(() => {
    virtualListRef.current?.setListData(data);
  }, [data.length]);

  useEffect(() => {
    virtualListRef.current?.setRenderItem(item => `<div style="height: 50px; width: 100%;">${item}</div>`);
  }, []);

  const handle = useCallback(() => {
    setData(prev =>
      prev.concat(
        Array(10)
          .fill(0)
          .map((_, idx) => (data[data.length - 1] || 0) + idx + 1),
      ),
    );
  }, []);

  return <TiVirtualList ref={virtualListRef} onLoad={handle} />;
};
